<?php

/**
 * Test-data seeder: gives 20 mahasiswa accounts a first self-assessment session
 * (one BDI-II + one PWB submission each, submitted together like the real
 * combined session flow) with results spread across all 6 combined risk levels,
 * so the Laporan reports have something varied to show.
 *
 * Only touches mahasiswa accounts that don't already have any assessment_submissions
 * row — safe to re-run, it will simply pick a different/empty set of candidates.
 *
 * Usage: php database/seeders/seed_test_assessments.php
 */

require __DIR__ . '/../../vendor/autoload.php';

use App\Core\Database;
use App\Services\AssessmentScoringService;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../..');
$dotenv->safeLoad();

$db = Database::connection();
$scoring = new AssessmentScoringService();

const BDI2_RANGES = [
    'Minimal' => [0, 13],
    'Ringan'  => [14, 19],
    'Sedang'  => [20, 28],
    'Berat'   => [29, 63],
];

// [min%, max%] per PWB category, matching AssessmentScoringService::pwbCategoryFromPercentage()
const PWB_RANGES = [
    'Rendah' => [30, 59],
    'Sedang' => [60, 79],
    'Tinggi' => [80, 98],
];

const PWB_DIM_MAX = 18;
const PWB_MAX = 108;

/** Splits $total across $count buckets, each capped at PWB_DIM_MAX, summing exactly to $total. */
function distributeAcrossDimensions(int $total, int $count): array
{
    $remaining = $total;
    $scores = [];
    for ($i = 0; $i < $count; $i++) {
        $slotsLeft = $count - $i;
        $maxForThis = min(PWB_DIM_MAX, $remaining);
        $minForThis = max(0, $remaining - PWB_DIM_MAX * ($slotsLeft - 1));
        $score = $slotsLeft === 1 ? $remaining : random_int($minForThis, max($minForThis, $maxForThis));
        $scores[] = $score;
        $remaining -= $score;
    }

    return $scores;
}

// 20 (pwb_category, bdi2_category) target pairs, chosen to spread across all 6
// combined risk levels (see AssessmentScoringService::combinedLevel()) instead of
// clustering at the extremes.
$targets = [
    ['Tinggi', 'Minimal'], ['Tinggi', 'Minimal'], ['Tinggi', 'Minimal'],                     // Level 1 - Sangat Rendah
    ['Tinggi', 'Ringan'], ['Sedang', 'Minimal'], ['Tinggi', 'Ringan'],                       // Level 2 - Rendah
    ['Tinggi', 'Sedang'], ['Sedang', 'Ringan'], ['Rendah', 'Minimal'], ['Sedang', 'Ringan'], // Level 3 - Rendah-Sedang
    ['Tinggi', 'Berat'], ['Sedang', 'Sedang'], ['Rendah', 'Ringan'], ['Sedang', 'Sedang'],   // Level 4 - Sedang
    ['Sedang', 'Berat'], ['Rendah', 'Sedang'], ['Sedang', 'Berat'], ['Rendah', 'Sedang'],    // Level 5 - Sedang-Tinggi
    ['Rendah', 'Berat'], ['Rendah', 'Berat'],                                                // Level 6 - Tinggi
];

$candidates = $db->query(
    "SELECT id, nama FROM users
     WHERE role = 'mahasiswa' AND status = 'active'
       AND id NOT IN (SELECT DISTINCT user_id FROM assessment_submissions)
     ORDER BY id LIMIT " . count($targets)
)->fetch_all(MYSQLI_ASSOC);

if (count($candidates) < count($targets)) {
    fwrite(STDERR, "Only " . count($candidates) . " mahasiswa without existing submissions found; need " . count($targets) . ". Aborting.\n");
    exit(1);
}

$sqlLog = "-- Generated by database/seeders/seed_test_assessments.php on " . date('Y-m-d H:i:s') . "\n";
$today = new DateTime();

foreach ($candidates as $i => $student) {
    [$pwbCategory, $bdi2Category] = $targets[$i];
    $userId = (int) $student['id'];

    // Submitted 1-45 days ago, spread out so date-range filters have something to filter.
    $daysAgo = random_int(1, 45);
    $submittedAt = (clone $today)->modify("-{$daysAgo} days")->format('Y-m-d H:i:s');

    // --- BDI-II ---
    [$bdiMin, $bdiMax] = BDI2_RANGES[$bdi2Category];
    $bdi2Total = random_int($bdiMin, $bdiMax);
    assert($scoring->bdi2Category($bdi2Total) === $bdi2Category);

    $type = 'bdi2';
    $maxBdi2 = 63;
    $stmt = $db->prepare(
        'INSERT INTO assessment_submissions
            (user_id, type, total_score, max_score, category, category_percentage, dimension_scores, is_timed_out, submitted_at)
         VALUES (?, ?, ?, ?, ?, NULL, NULL, 0, ?)'
    );
    $stmt->bind_param('isiiss', $userId, $type, $bdi2Total, $maxBdi2, $bdi2Category, $submittedAt);
    $stmt->execute();
    $sqlLog .= "INSERT INTO assessment_submissions (user_id, type, total_score, max_score, category, submitted_at) VALUES ({$userId}, 'bdi2', {$bdi2Total}, 63, '{$bdi2Category}', '{$submittedAt}');\n";

    // --- PWB (6 dimensions, each 0-18, summing to the target total) ---
    [$pctMin, $pctMax] = PWB_RANGES[$pwbCategory];
    $percentage = random_int($pctMin, $pctMax);
    $pwbTotal = (int) round($percentage / 100 * PWB_MAX);
    assert($scoring->pwbCategoryFromPercentage($percentage) === $pwbCategory);

    $dims = array_keys(AssessmentScoringService::PWB_DIMENSIONS);
    $dimScores = distributeAcrossDimensions($pwbTotal, count($dims));

    $dimensionScores = [];
    foreach ($dims as $idx => $dimKey) {
        $dScore = $dimScores[$idx];
        $dPct = round($dScore / PWB_DIM_MAX * 100, 2);
        $dCategory = $scoring->pwbCategoryFromPercentage($dPct);
        $dimensionScores[$dimKey] = [
            'label'      => AssessmentScoringService::PWB_DIMENSIONS[$dimKey],
            'score'      => $dScore,
            'max_score'  => PWB_DIM_MAX,
            'percentage' => $dPct,
            'category'   => $dCategory,
            'feedback'   => $scoring->pwbDimensionFeedback($dimKey, $dCategory),
        ];
    }
    $dimensionJson = json_encode($dimensionScores);

    $type = 'pwb';
    $maxPwb = PWB_MAX;
    $pctFloat = (float) $percentage;
    $stmt2 = $db->prepare(
        'INSERT INTO assessment_submissions
            (user_id, type, total_score, max_score, category, category_percentage, dimension_scores, is_timed_out, submitted_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)'
    );
    $stmt2->bind_param('isiisdss', $userId, $type, $pwbTotal, $maxPwb, $pwbCategory, $pctFloat, $dimensionJson, $submittedAt);
    $stmt2->execute();
    $sqlLog .= "INSERT INTO assessment_submissions (user_id, type, total_score, max_score, category, category_percentage, dimension_scores, submitted_at) VALUES ({$userId}, 'pwb', {$pwbTotal}, 108, '{$pwbCategory}', {$percentage}, '" . addslashes($dimensionJson) . "', '{$submittedAt}');\n";

    $combined = $scoring->combinedLevel($pwbCategory, $bdi2Category);
    echo sprintf(
        "#%-2d %-20s PWB=%s(%d%%) BDI2=%s(%d) -> Level %d (%s)\n",
        $i + 1,
        $student['nama'],
        $pwbCategory,
        $percentage,
        $bdi2Category,
        $bdi2Total,
        $combined['level'],
        $combined['risk_label']
    );
}

file_put_contents(__DIR__ . '/seed_test_assessments.generated.sql', $sqlLog);
echo "\nDone. " . count($candidates) . " students seeded. Generated SQL log written to database/seeders/seed_test_assessments.generated.sql\n";
